version: '2'
services:
  php:
    container_name: lemp_php
    build: ./website/php/
    restart: unless-stopped
    volumes:
      - ./website/html/:/var/www/html
    expose:
      - "9000"
    depends_on:
      - db

  nginx:
    container_name: lemp_nginx
    image: nginx:stable-alpine
    restart: unless-stopped

    environment: 
      VIRTUAL_HOST: www.jameslnwza.com
      LETSENCRYPT_HOST: www.jameslnwza.com

    volumes:
      - ./website/html/:/var/www/html
      - ./website/nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./website/nginx/conf.d:/etc/nginx/conf.d:ro
    expose: 
      - "80"

  db:
    container_name: lemp_mariadb
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - ./website/mariadb/initdb/:/docker-entrypoint-initdb.d
      - ./website/mariadb/data/:/var/lib/mysql/

    environment:
      - MYSQL_ROOT_PASSWORD=devops101
      - MYSQL_DATABASE=devops_db
      - MYSQL_USER=devops
      - MYSQL_PASSWORD=devops101
  
  pma:
    container_name: lemp-phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always

    environment: 
      VIRTUAL_HOST: mydb.jameslnwza.com
      LETSENCRYPT_HOST: mydb.jameslnwza.com
    expose: 
      - "80"

  # cert:
  #   container_name: lemp-cert
  #   image: neilpang/acme.sh:latest
  #   restart: always
  #   volumes:
  #     - ./proxy-config/cert:/etc/nginx/conf.d/cert
  #   command: >
  #     bash -c  "
  #         acme.sh --install-cert -d jameslnwza.com -d mydb.jameslnwza.com -d www.jameslnwza.com \
  #     --key-file       /etc/nginx/conf.d/cert/ssl.jameslnwza-cert.key  \
  #     --fullchain-file /etc/nginx/conf.d/cert/ssl.jameslnwza-cert.pem \
  #     --reloadcmd     'service nginx force-reload'
  #     "


  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: lemp-cert
    volumes: 
      - ./proxy-config/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on: 
      - nginx

  proxy:
    container_name: lemp-proxy
    image:  nginx:stable-alpine
    restart: always
    volumes: 
      - ./proxy-config:/etc/nginx/conf.d

    ports: 
      # - host:container
      - "80:80"
      - "443:443"